version: '3.9'

services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: always

    ports:
      - "${BACKEND_PORT}:3000"

    depends_on:
      - mongodb

    env_file:
      - .env

    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always

    ports:
      - "${FRONTEND_PORT}:80"

    depends_on:
      - backend

    networks:
      - app-network

  monitor:
    build: ./monitor-servicios
    container_name: monitor
    restart: always

    ports:
      - "${MONITOR_PORT}:4000"

    depends_on:
      - backend
      - frontend
      - mongodb

    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network: